"""Local neural embeddings for the SOFIA knowledge base.

Embeddings are generated by Ollama on the local machine.  The cache contains
only derived vectors and source coordinates, never the extracted document
text, questions or answers.  This keeps the semantic index useful without
turning it into a second copy of sensitive knowledge.
"""

from __future__ import annotations

import hashlib
import json
import logging
import math
import os
import tempfile
import threading
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import httpx

from .expansion import ExpansionStore, _connect, expansion_storage_status
from .ingestion import files_for, ingest_module

logger = logging.getLogger("sofia.embeddings")

DEFAULT_MODEL = "nomic-embed-text"
DEFAULT_HOST = "http://127.0.0.1:11434"

# The module/status endpoints are polled by the browser.  Probing Ollama once
# for every module made a normal UI refresh take roughly ``module_count * 2s``
# when Ollama was cold or unavailable.  Keep the health probe process-local and
# reuse it for a short interval; embedding generation still has its own request
# timeout and remains independent from this status cache.
_OLLAMA_PROBE_CACHE: dict[str, tuple[float, bool, list[str], str | None]] = {}
_OLLAMA_PROBE_LOCK = threading.Lock()


def _truthy(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().casefold() in {"1", "true", "yes", "on", "sim"}


def embedding_settings() -> dict[str, Any]:
    try:
        max_chunks = max(100, min(30000, int(os.getenv("SOFIA_EMBEDDING_MAX_CHUNKS", "100"))))
    except ValueError:
        max_chunks = 100
    try:
        batch_size = max(1, min(64, int(os.getenv("SOFIA_EMBEDDING_BATCH_SIZE", "32"))))
    except ValueError:
        batch_size = 16
    try:
        timeout = max(1.0, min(180.0, float(os.getenv("SOFIA_EMBEDDING_TIMEOUT_SECONDS", "120"))))
    except ValueError:
        timeout = 120.0
    try:
        query_timeout = max(0.5, min(15.0, float(os.getenv("SOFIA_EMBEDDING_QUERY_TIMEOUT_SECONDS", "3"))))
    except ValueError:
        query_timeout = 3.0
    return {
        "enabled": _truthy(os.getenv("SOFIA_EMBEDDINGS_ENABLED"), True),
        "query_enabled": _truthy(os.getenv("SOFIA_EMBEDDINGS_QUERY_ENABLED"), True),
        "model": os.getenv("OLLAMA_EMBEDDING_MODEL", DEFAULT_MODEL).strip() or DEFAULT_MODEL,
        "host": os.getenv("OLLAMA_HOST", DEFAULT_HOST).strip().rstrip("/"),
        "max_chunks": max_chunks,
        "batch_size": batch_size,
        "timeout_seconds": timeout,
        "query_timeout_seconds": query_timeout,
    }


def _cache_path(root: Path, module_id: str) -> Path:
    return root.parent / "data" / "semantic-embeddings" / f"{module_id}.json"


def _corpus_signature(root: Path, module_id: str) -> str:
    digest = hashlib.sha256()
    for path in files_for(root, module_id):
        stat = path.stat()
        digest.update(str(path.relative_to(root)).encode("utf-8", "replace"))
        digest.update(str(stat.st_mtime_ns).encode())
        digest.update(str(stat.st_size).encode())
    return digest.hexdigest()


def _ollama_probe_ttl() -> float:
    try:
        return max(5.0, min(300.0, float(os.getenv("SOFIA_OLLAMA_PROBE_TTL_SECONDS", "30"))))
    except ValueError:
        return 30.0


def _ollama_models(settings: dict[str, Any], *, force: bool = False) -> tuple[bool, list[str], str | None]:
    cache_key = str(settings["host"])
    now = time.monotonic()
    with _OLLAMA_PROBE_LOCK:
        cached = _OLLAMA_PROBE_CACHE.get(cache_key)
        if cached and not force and now - cached[0] < _ollama_probe_ttl():
            return cached[1], list(cached[2]), cached[3]
    try:
        with httpx.Client(base_url=settings["host"], timeout=2.0) as client:
            response = client.get("/api/tags")
            response.raise_for_status()
            models = [str(item.get("name", "")) for item in response.json().get("models", []) if item.get("name")]
            result = (True, models, None)
    except (httpx.HTTPError, ValueError, OSError) as exc:
        result = (False, [], f"{type(exc).__name__}: {str(exc)[:180]}")
    with _OLLAMA_PROBE_LOCK:
        _OLLAMA_PROBE_CACHE[cache_key] = (time.monotonic(), result[0], list(result[1]), result[2])
    return result


def _embed_batch(texts: list[str], settings: dict[str, Any], timeout: float | None = None) -> list[list[float]]:
    with httpx.Client(base_url=settings["host"], timeout=timeout or settings["timeout_seconds"]) as client:
        response = client.post("/api/embed", json={"model": settings["model"], "input": texts})
        response.raise_for_status()
        payload = response.json()
        embeddings = payload.get("embeddings")
        if not isinstance(embeddings, list) or len(embeddings) != len(texts):
            raise RuntimeError("Ollama retornou uma quantidade de embeddings diferente da entrada")
        result: list[list[float]] = []
        for vector in embeddings:
            if not isinstance(vector, list) or not vector:
                raise RuntimeError("Ollama retornou um embedding inválido")
            result.append([float(value) for value in vector])
        return result


def _embedding_text(text: str) -> str:
    """Keep both the opening definition and the closing qualification of a chunk."""
    if len(text) <= 1200:
        return text
    return f"{text[:760]}\n{text[-440:]}"


def _load_cache(root: Path, module_id: str) -> dict[str, Any] | None:
    path = _cache_path(root, module_id)
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(payload, dict) or payload.get("module_id") != module_id:
        return None
    if payload.get("corpus_signature") != _corpus_signature(root, module_id):
        return None
    if not isinstance(payload.get("items"), list) or not payload["items"]:
        return None
    return payload


def _cache_complete_for(payload: dict[str, Any], settings: dict[str, Any]) -> bool:
    indexed_chunks = payload.get("indexed_chunks")
    chunk_count = payload.get("chunk_count")
    if not isinstance(indexed_chunks, int) or not isinstance(chunk_count, int):
        return True
    return indexed_chunks >= min(settings["max_chunks"], chunk_count)


def _cache_label(payload: dict[str, Any]) -> str:
    indexed_chunks = payload.get("indexed_chunks")
    chunk_count = payload.get("chunk_count")
    if isinstance(indexed_chunks, int) and isinstance(chunk_count, int) and indexed_chunks < chunk_count:
        return "partial"
    return "ready"


def _write_cache(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=f"{path.stem}-", suffix=".tmp", dir=path.parent)
    os.close(fd)
    temporary = Path(temporary_name)
    try:
        temporary.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def _persist_postgres(root: Path, module_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    """Persist derived vectors in PostgreSQL when the runtime store is ready."""
    if expansion_storage_status()["backend"] != "postgresql":
        return {"backend": expansion_storage_status()["backend"], "persisted": False}
    store = ExpansionStore(root)
    connection: Any | None = None
    try:
        store.initialize()
        connection = _connect(store.path)
        connection.execute("DELETE FROM semantic_embeddings WHERE module_id = ? AND model = ?", (module_id, payload["model"]))
        for item in payload["items"]:
            connection.execute(
                "INSERT INTO semantic_embeddings (module_id, source_path, ordinal, source_hash, model, dimension, vector_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (module_id, item["source_path"], item["ordinal"], payload["corpus_signature"], payload["model"], payload["dimension"], json.dumps(item["vector"], separators=(",", ":")), payload["generated_at"]),
            )
        connection.commit()
        return {"backend": "postgresql", "persisted": True}
    except Exception as exc:  # noqa: BLE001  # pragma: no cover - deployment database dependent.
        logger.warning("Não foi possível persistir embeddings no PostgreSQL: %s", exc)
        return {"backend": "postgresql", "persisted": False, "error": f"{type(exc).__name__}: {str(exc)[:180]}"}
    finally:
        if connection is not None:
            connection.close()


def build_module_embeddings(root: Path, module_id: str, force: bool = False) -> dict[str, Any]:
    settings = embedding_settings()
    if not settings["enabled"]:
        return {"module_id": module_id, "status": "disabled", "items": 0, "model": settings["model"]}
    if not force:
        cached = _load_cache(root, module_id)
        if cached and _cache_complete_for(cached, settings):
            return {
                "module_id": module_id,
                "status": _cache_label(cached),
                "items": len(cached["items"]),
                "chunk_count": cached.get("chunk_count", len(cached["items"])),
                "dimension": cached.get("dimension", 0),
                "model": cached["model"],
                "storage": _persist_postgres(root, module_id, cached),
            }
    available, models, error = _ollama_models(settings)
    if not available:
        return {"module_id": module_id, "status": "unavailable", "items": 0, "model": settings["model"], "error": error}
    model_name = settings["model"]
    if model_name not in models and not any(name.split(":", 1)[0] == model_name.split(":", 1)[0] for name in models):
        return {
            "module_id": module_id,
            "status": "model-missing",
            "items": 0,
            "model": model_name,
            "available_models": models,
            "error": f"Modelo de embedding não instalado: {model_name}",
        }
    all_chunks = ingest_module(root, module_id)
    if not all_chunks:
        return {"module_id": module_id, "status": "empty", "items": 0, "model": model_name}
    chunk_count = len(all_chunks)
    chunks = all_chunks[: settings["max_chunks"]]
    items: list[dict[str, Any]] = []
    try:
        for start in range(0, len(chunks), settings["batch_size"]):
            batch = chunks[start : start + settings["batch_size"]]
            vectors = _embed_batch([_embedding_text(item.text) for item in batch], settings)
            for chunk, vector in zip(batch, vectors):
                items.append({"source_path": str(chunk.path.relative_to(root)), "ordinal": chunk.ordinal, "vector": vector})
    except (httpx.HTTPError, OSError, RuntimeError, ValueError) as exc:
        logger.warning("Falha ao gerar embeddings de %s: %s", module_id, exc)
        return {"module_id": module_id, "status": "failed", "items": len(items), "model": model_name, "error": f"{type(exc).__name__}: {str(exc)[:220]}"}
    dimension = len(items[0]["vector"]) if items else 0
    payload = {
        "version": 1,
        "module_id": module_id,
        "model": model_name,
        "dimension": dimension,
        "chunk_count": chunk_count,
        "indexed_chunks": len(chunks),
        "corpus_signature": _corpus_signature(root, module_id),
        "generated_at": datetime.now(UTC).isoformat(),
        "items": items,
    }
    _write_cache(_cache_path(root, module_id), payload)
    return {"module_id": module_id, "status": "partial" if len(items) < chunk_count else "ready", "items": len(items), "chunk_count": chunk_count, "dimension": dimension, "model": model_name, "storage": _persist_postgres(root, module_id, payload)}


def build_all_embeddings(root: Path, module_ids: list[str], force: bool = False) -> dict[str, Any]:
    """Build one module at a time to keep CPU/RAM bounded on the target host."""
    results = []
    for module_id in module_ids:
        results.append(build_module_embeddings(root, module_id, force=force))
    return {"status": "completed", "modules": results, "sequential": True}


def embedding_status(root: Path, module_id: str | None = None) -> dict[str, Any]:
    settings = embedding_settings()
    available, models, error = _ollama_models(settings)
    module_ids = [module_id] if module_id else sorted(path.name for path in root.iterdir() if path.is_dir())
    caches = []
    for current in module_ids:
        payload = _load_cache(root, current)
        caches.append({"module_id": current, "status": _cache_label(payload) if payload else "pending", "items": len(payload["items"]) if payload else 0, "chunk_count": payload.get("chunk_count", len(payload["items"])) if payload else 0, "dimension": payload.get("dimension", 0) if payload else 0})
    return {"enabled": settings["enabled"], "query_enabled": settings["query_enabled"], "model": settings["model"], "max_chunks_per_module": settings["max_chunks"], "ollama_available": available, "available_models": models, "error": error, "storage": expansion_storage_status(), "modules": caches}


def _cosine(left: list[float], right: list[float]) -> float:
    dot = sum(a * b for a, b in zip(left, right))
    left_norm = math.sqrt(sum(value * value for value in left))
    right_norm = math.sqrt(sum(value * value for value in right))
    return dot / (left_norm * right_norm) if left_norm and right_norm else 0.0


def semantic_scores(root: Path, module_id: str, query: str) -> dict[tuple[str, int], float]:
    """Return optional local neural scores; failures never block lexical RAG."""
    settings = embedding_settings()
    if not settings["enabled"] or not settings["query_enabled"] or not query.strip():
        return {}
    cache = _load_cache(root, module_id)
    if not cache or cache.get("model") != settings["model"]:
        return {}
    try:
        query_vector = _embed_batch([_embedding_text(query)], settings, timeout=settings["query_timeout_seconds"])[0]
    except (httpx.HTTPError, OSError, RuntimeError, ValueError):
        return {}
    scores: dict[tuple[str, int], float] = {}
    for item in cache["items"]:
        vector = item.get("vector")
        if not isinstance(vector, list):
            continue
        scores[(str(root / item["source_path"]), int(item["ordinal"]))] = max(0.0, _cosine(query_vector, [float(value) for value in vector]))
    return scores
