from __future__ import annotations

import re
import unicodedata
from dataclasses import asdict, dataclass, field
from typing import Any

from .domains import DOMAIN_CONTRACTS


def normalize(text: str) -> str:
    """Normalize accents and case for intent matching without changing evidence."""
    return "".join(
        char
        for char in unicodedata.normalize("NFKD", text.casefold())
        if not unicodedata.combining(char)
    )


SLEEP_MARKERS = (
    "piscada de sono",
    "piscadas de sono",
    "microssono",
    "micro sono",
    "sono durante o dia",
    "sonolencia diurna",
    "sonolencia durante o dia",
    "dormir pouco",
    "dormindo pouco",
    "sono insuficiente",
    "adormecer durante o dia",
    "ataque de sono",
    "trechos de sono",
)


def is_medical_sleep_query(question: str) -> bool:
    normalized = normalize(question)
    return any(marker in normalized for marker in SLEEP_MARKERS) or (
        any(term in normalized for term in ("sonolencia", "sono", "dormir", "adormecer"))
        and any(term in normalized for term in ("dia", "horas", "irritacao", "irritabilidade", "segundos", "5 horas"))
    )


MODULE_NAMES = {module_id: contract.name for module_id, contract in DOMAIN_CONTRACTS.items()}
MODULE_SCOPE_TERMS = {
    module_id: contract.keywords for module_id, contract in DOMAIN_CONTRACTS.items()
}

# A module assistant may keep a friendly conversation, but it must not turn an
# obviously unrelated task into an answer generated by the active module.  The
# list is intentionally conservative: these are high-signal topic markers,
# not a generic deny-list.  Adding a new module does not require changing this
# policy; it only needs a new topic family when the product introduces an
# explicitly supported vertical outside the institutional registry.
OUT_OF_SCOPE_TOPIC_TERMS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "culinária",
        (
            "pão",
            "paes",
            "pães",
            "receita",
            "cozinhar",
            "cozinha",
            "ingrediente",
            "forno",
            "assar",
            "bolo",
            "pizza",
        ),
    ),
    (
        "esportes",
        (
            "futebol",
            "gol",
            "gols",
            "campeonato",
            "partida",
            "jogo",
            "time de futebol",
        ),
    ),
    (
        "viagens e turismo",
        (
            "viagem",
            "hotel",
            "passagem aérea",
            "voo",
            "turismo",
            "roteiro turístico",
        ),
    ),
)

GENERIC_ANALYSIS_TERMS = (
    "resumo",
    "resuma",
    "conteudo",
    "conteúdo",
    "ponto",
    "pontos",
    "positivo",
    "positivos",
    "negativo",
    "negativos",
    "aspecto",
    "aspectos",
    "abordad",
    "analise",
    "análise",
    "vantagem",
    "desvantagem",
)

# Some modules intentionally cover the same operational subject.  A single
# labour term must not be treated as a cross-domain violation when the user is
# in Direito or Departamento Pessoal: both modules can legitimately answer
# questions about jornada, horas extras and empregados, with different source
# policies.  This table keeps the scope gate strict for genuinely unrelated
# domains while making the overlap explicit and testable.
SHARED_MODULE_SCOPE_TERMS: dict[frozenset[str], tuple[str, ...]] = {
    frozenset({"direito", "departamento-pessoal"}): (
        "hora extra",
        "jornada",
        "empregado",
        "clt",
        "ferias",
        "rescisao",
        "folha",
    ),
}


def _is_shared_scope_term(current: str, candidate: str, term: str) -> bool:
    pair = frozenset({current, candidate})
    normalized_term = normalize(term)
    return normalized_term in {
        normalize(item) for item in SHARED_MODULE_SCOPE_TERMS.get(pair, ())
    }


def _explicit_out_of_scope_topic(normalized: str, current_score: int) -> tuple[str, list[str]] | None:
    """Return a high-signal external topic without blocking normal chat.

    ``assess_module_scope`` must distinguish an open conversation opener from a
    concrete task.  A message such as ``me ajuda`` has no topic and remains
    conversational; ``quero fazer pão`` has a concrete, recognizable topic and
    must stop at the module boundary before any provider is called.
    """

    if current_score > 0:
        return None
    for topic, terms in OUT_OF_SCOPE_TOPIC_TERMS:
        matched = [term for term in terms if normalize(term) in normalized]
        if matched:
            return topic, matched[:4]
    return None


DIRECT_CONVERSATION_MARKERS = (
    "oi",
    "ola",
    "olá",
    "bom dia",
    "boa tarde",
    "boa noite",
    "obrigado",
    "obrigada",
    "quem e voce",
    "quem é você",
    "como voce pode ajudar",
    "como você pode ajudar",
    "como voce esta",
    "como você está",
    "como vc esta",
    "como vc está",
    "tudo bem",
    "tudo certo",
    "como vai",
)

DIRECT_WRITING_MARKERS = (
    "escreva",
    "redija",
    "reescreva",
    "reformule",
    "melhore este texto",
    "melhore esse texto",
    "corrija este texto",
    "corrija esse texto",
    "crie um email",
    "crie um e-mail",
    "escreva um email",
    "escreva um e-mail",
    "crie uma mensagem",
    "escreva uma mensagem",
    "traduza",
)

EVIDENCE_REQUEST_MARKERS = (
    "arquivo",
    "documento",
    "documentos",
    "fonte",
    "fontes",
    "link",
    "links",
    "base local",
    "base de conhecimento",
    "segundo",
    "conforme",
    "de acordo com",
    "no acordo",
    "na lei",
    "no contrato",
    "na imagem",
    "no csv",
    "no xlsx",
    "compare",
    "comparar",
    "jurisprudencia",
    "jurisprudência",
    "resuma",
    "resumo",
    "listar documentos",
    "o que temos sobre",
    "o que diz",
    "o que consta",
    "o que estabelece",
    "acordo coletivo",
    "convencao coletiva",
    "convenção coletiva",
    "vade mecum",
    "saae",
    "jurisprudencia",
    "jurisprudência",
    "prazo",
    "artigo",
    "clausula",
    "cláusula",
    "linha",
    "linhas",
    "termo exato",
    "trecho exato",
    "mandado de seguranca",
    "mandado de segurança",
    "enap",
    "escola virtual",
    "csv",
    "xlsx",
    "planilha",
    "tabela",
)

OPEN_CONVERSATION_MARKERS = (
    "me ajuda",
    "pode me ajudar",
    "preciso de ajuda",
    "tenho um problema",
    "estou com um problema",
    "posso te explicar",
    "posso explicar",
    "quero te explicar",
    "quero te contar",
    "vou te contar",
    "o que voce acha",
    "o que você acha",
    "me orienta",
    "preciso conversar",
    "posso falar",
    "tenho uma situacao",
    "tenho uma situação",
)

GENERAL_EXPLANATION_MARKERS = (
    "o que e ",
    "o que é ",
    "qual a diferenca",
    "qual é a diferença",
    "explique ",
    "me explique ",
    "como funciona",
    "fale sobre ",
    "defina ",
    "o que significa ",
    "por que ",
    "porque ",
    "como ",
)

PROCEDURE_MARKERS = (
    "como criar",
    "como configurar",
    "como definir",
    "como que defino",
    "como que configuro",
    "como que crio",
    "como faço para",
    "como faco para",
    "como organizar",
    "como vejo",
    "como identificar",
    "como acompanhar",
    "como analisar",
    "como medir",
    "como adicionar",
    "como cadastrar",
    "como executar",
    "qual o procedimento",
    "passo a passo",
)

TOOL_ACTION_MARKERS = (
    "execute ",
    "executar ",
    "reinicie ",
    "reiniciar ",
    "altere ",
    "alterar ",
    "aplique ",
    "aplicar ",
    "sincronize ",
    "sincronizar ",
)

STRUCTURED_MARKERS = (
    "quantos",
    "quantas",
    "soma",
    "media",
    "média",
    "total",
    "conte",
    "contagem",
    "csv",
    "xlsx",
    "planilha",
    "tabela",
)

COMPLEX_REASONING_MARKERS = (
    "infer",
    "correlac",
    "padrao",
    "padrão",
    "causal",
    "relacione",
    "relacionar",
    "recomende",
    "recomendação",
    "cenário",
    "cenario",
    "prejuiz",
    "root cause",
    "causa raiz",
    "causa do incidente",
    "por que falhou",
    "porque falhou",
    "analise do incidente",
)


def _route_payload(
    route: str,
    task_route: str,
    retrieval_required: bool,
    response_mode: str,
    reason: str,
) -> dict[str, Any]:
    """Return the public route contract with a stable legacy alias.

    ``route`` remains compatible with the existing orchestration stages;
    ``task_route`` is the stricter task taxonomy used by the new router and
    observability.  Keeping both avoids breaking old clients while making it
    impossible to confuse a conversational task with document retrieval.
    """
    return {
        "route": route,
        "task_route": task_route,
        "retrieval_required": retrieval_required,
        "response_mode": response_mode,
        "reason": reason,
    }


def _has_explicit_evidence_request(compact: str) -> bool:
    return any(
        re.search(rf"\b{re.escape(marker)}\b", compact)
        if re.fullmatch(r"[\wÀ-ÿ]+", marker)
        else marker in compact
        for marker in EVIDENCE_REQUEST_MARKERS
    )


def is_explicit_evidence_request(question: str) -> bool:
    """Return whether the user explicitly anchored the request to a source.

    Scope protection must not block a law, manual or file that intentionally
    lives in the active module, even when its subject uses vocabulary from a
    different domain.  This is the exception to the cross-domain gate.
    """

    normalized = normalize(question)
    return _has_explicit_evidence_request(normalized) or bool(
        re.search(r"\b[\w-]+\.(?:md|txt|pdf|docx|xlsx|csv|xml|json)\b", normalized)
    ) or any(
        re.search(rf"\b{re.escape(marker)}\b", normalized)
        if re.fullmatch(r"[\wÀ-ÿ]+", marker)
        else marker in normalized
        for marker in (
            "manual",
            "norma",
            "lei",
            "vade",
            "saae",
            "acordo coletivo",
            "convencao coletiva",
        )
    )


def _has_conversation_follow_up(
    question: str, history: list[dict[str, str]] | None
) -> bool:
    """Keep only genuinely conversational continuations on the chat route.

    The old implementation looked only at the last assistant message.  Once
    Sofia asked ``me conte o que aconteceu``, every next user turn inherited
    the conversation route, including concrete legal/technical questions.  A
    follow-up may remain conversational only when the current turn is short
    and does not contain an interrogative or a domain task marker.
    """

    if not history:
        return False
    normalized = normalize(question).strip()
    words = normalized.split()
    if len(words) > 7:
        return False
    if any(
        marker in normalized
        for marker in (
            "o que ",
            "qual ",
            "quais ",
            "como ",
            "por que ",
            "porque ",
            "quando ",
            "onde ",
            "quanto ",
            "quantos ",
            "quantas ",
            "e possivel",
            "é possível",
            "fale sobre",
            "explique",
            "defina",
            "resuma",
            "compare",
            "documento",
            "arquivo",
            "lei",
            "artigo",
            "norma",
            "acordo",
            "jornada",
            "hora extra",
            "tosse",
            "gripe",
            "zabbix",
        )
    ):
        return False
    for item in reversed(history[-6:]):
        if item.get("role") != "assistant":
            continue
        text = normalize(str(item.get("content", "")))
        if any(
            marker in text
            for marker in (
                "me conte",
                "o que aconteceu",
                "qual situacao",
                "qual situação",
                "pode explicar",
                "conte mais",
                "como posso ajudar",
            )
        ):
            return True
        break
    return False


def recent_documentary_answer(history: list[dict[str, str]] | None) -> str:
    """Return the latest bounded assistant answer that carries local evidence."""

    for item in reversed((history or [])[-8:]):
        if item.get("role") != "assistant":
            continue
        content = str(item.get("content", "")).strip()
        normalized = normalize(content)
        if any(marker in normalized for marker in ("fontes e trechos", "base documental", "fato documentado", "documento local")):
            return content[:2200]
    return ""


def recent_documentary_question(history: list[dict[str, str]] | None) -> str:
    """Return the user question that produced the latest local evidence."""

    items = list((history or [])[-8:])
    for index in range(len(items) - 1, -1, -1):
        item = items[index]
        if item.get("role") != "assistant":
            continue
        content = str(item.get("content", ""))
        if not any(marker in normalize(content) for marker in ("fontes e trechos", "base documental", "fato documentado", "documento local")):
            continue
        for previous in reversed(items[:index]):
            if previous.get("role") == "user" and str(previous.get("content", "")).strip():
                return str(previous["content"]).strip()[:1600]
    return ""


def requested_exact_term(question: str) -> str:
    """Extract the literal subject of a ``qual linha/onde está`` request."""

    text = str(question or "").strip()
    if not re.search(r"\b(?:linha|linhas|line|lines)\b", normalize(text)):
        return ""
    quoted = re.findall(r"[\"“”']([^\"“”']{3,240})[\"“”']", text)
    if quoted:
        return re.sub(r"\s+", " ", quoted[-1]).strip(" .,:;?!")
    match = re.search(r"(?:termo|trecho|texto)\s+(?:aqui)?\s*[?:-]?\s*(.+)$", text, flags=re.IGNORECASE)
    if not match:
        return ""
    candidate = re.sub(r"\s+", " ", match.group(1)).strip(" .,:;?!")
    if not candidate or re.fullmatch(r"\d+(?:\s*(?:-|a|até|to)\s*\d+)?", candidate, flags=re.IGNORECASE):
        return ""
    return candidate[:240]


def _list_elements_requested(question: str) -> bool:
    normalized = normalize(question)
    return any(
        marker in normalized
        for marker in (
            "quais outros",
            "que outros",
            "pode me citar outros",
            "cite outros",
            "liste",
            "listar",
            "quais cursos",
            "outros cursos",
            "outros exemplos",
            "me cite exemplos",
        )
    ) and not comparison_requested_for_plan(normalized)


def comparison_requested_for_plan(question: str) -> bool:
    normalized = normalize(question)
    return any(
        marker in normalized
        for marker in (
            "compare",
            "comparar",
            "comparando",
            "diferenca entre",
            "confronte",
            "cruze os",
            "relacione os documentos",
            "entre os documentos",
            "comum e diferente",
            "o que ha em comum",
            "o que existe em comum",
            "pontos em comum",
            "diferencas entre os dois",
            "diferencas entre ambos",
        )
    )


def decompose_query(question: str) -> tuple[str, ...]:
    """Break a substantive request into retrievable user tasks.

    Retrieval used to receive one long string for a turn containing several
    questions.  A single TF-IDF/vector ranking then favoured one clause and
    the answer composer silently answered only that clause.  This helper is
    deliberately deterministic: punctuation and explicit interrogative
    connectors create tasks, while the original wording is preserved for the
    final response.

    It is not a sentence summarizer and it never changes document text.  A
    single ordinary question still produces a one-item tuple, so callers can
    keep the fast path for the common case.
    """

    raw = str(question or "").strip()
    if not raw:
        return ()
    # Session metadata is useful to retrieval, but it is not another user
    # task.  Excluding it here prevents labels such as ``Fonte ativa`` from
    # becoming lexical evidence in a compound query.
    raw = re.split(r"\n\s*(?:Contexto documental anterior da sessão|Fonte ativa da sessão)\s*:", raw, maxsplit=1, flags=re.IGNORECASE)[0].strip()
    pieces = re.split(r"(?<=[?!])\s+|\n+|;\s*", raw)
    tasks: list[str] = []
    connector = re.compile(
        r"\s+(?=(?:e\s+|tamb[eé]m\s+|al[eé]m\s+disso\s+)"
        r"(?:o\s+que|qual(?:\s+é|\s+s[aã]o)?|quais|por\s+que|porque)\b)",
        re.IGNORECASE,
    )
    for piece in pieces:
        current = piece.strip(" \t\r\n-•")
        if not current:
            continue
        for candidate in connector.split(current):
            value = re.sub(r"^(?:e|tamb[eé]m|al[eé]m disso)\s+", "", candidate.strip(), flags=re.IGNORECASE)
            value = re.sub(r"\s+", " ", value).strip(" \t\r\n-•")
            if len(re.findall(r"[\wÀ-ÿ]+", value)) < 4:
                continue
            if not value.endswith(("?", ".")) and "?" in current:
                value += "?"
            if normalize(value) not in {normalize(item) for item in tasks}:
                tasks.append(value)
    if not tasks:
        return (raw,)

    # In a compound turn, phrases such as “O que o SAAE?” and “E o que diz o
    # Vade?” are source hand-offs, not independent subjects.  Searching them
    # literally retrieves a cover, index or unrelated page from the named
    # document.  Attach each hand-off to the last substantive task so the
    # source selector keeps the user's actual topic.
    def source_only(value: str) -> bool:
        compact = normalize(value).strip(" ?.!:")
        return bool(
            re.fullmatch(
                r"(?:e\s+)?(?:o\s+que(?:\s+diz)?|qual(?:\s+e|\s+é)?|"
                r"o\s+que\s+informa)\s+(?:o\s+|a\s+)?"
                r"(?:saae|vade|vade\s+mecum|mecum)",
                compact,
            )
        )

    def contextual_follow_up(value: str) -> bool:
        compact = normalize(value)
        return source_only(value) or any(
            marker in compact
            for marker in (
                "nesse ponto",
                "nesta forma de trabalhar",
                "nesse caso",
                "isso e correto",
                "isso acontece",
                "qual falha",
                "quais falhas",
                "nao deveria",
                "o que ha de comum",
                "o que existe em comum",
                "diferente entre os dois",
                "diferente entre ambos",
            )
        )

    adjusted: list[str] = []
    anchor = ""
    for task in tasks:
        if contextual_follow_up(task) and anchor:
            task = f"{anchor} — {task}"
        else:
            anchor = task
        if normalize(task) not in {normalize(item) for item in adjusted}:
            adjusted.append(task)
    return tuple(adjusted)


def normalize_query_shorthand(text: str) -> str:
    """Normalize common chat shorthand for routing only.

    The original evidence must never be rewritten.  This small boundary lets
    ``oq`` and ``q`` behave like their full Portuguese forms when a user is
    continuing a conversation, without changing document text or citations.
    """

    normalized = normalize(text)
    normalized = re.sub(r"\boq\b", "o que", normalized)
    normalized = re.sub(r"\bq\b", "que", normalized)
    return re.sub(r"\s+", " ", normalized).strip()


def is_ambiguous_follow_up(question: str) -> bool:
    """Identify a short follow-up whose subject lives in session memory."""

    normalized = normalize_query_shorthand(question)
    words = normalized.split()
    if len(words) > 10:
        return False
    compact = re.sub(r"[!?.,;:]+", " ", normalized)
    compact = re.sub(r"\s+", " ", compact).strip()
    if re.fullmatch(r"(?:entao\s+)?o que pode ser", compact):
        return True
    if re.fullmatch(r"(?:entao\s+)?qual a causa", compact):
        return True
    if re.fullmatch(r"(?:entao\s+)?e agora", compact):
        return True
    if re.fullmatch(r"(?:entao\s+)?como assim", compact):
        return True
    meaningful = [
        word for word in words
        if word not in {"entao", "agora", "o", "que", "pode", "ser", "qual", "a", "e", "isso", "esse", "essa", "ele", "ela", "sim"}
    ]
    return not meaningful and bool(words)


def is_document_source_follow_up(question: str) -> bool:
    """Recognize a source handoff that still belongs to the prior question.

    Users often introduce the handoff with conversational padding, for
    example ``Entendi, e quando falamos do Vade, o que ele diz sobre isso?``.
    Treating that sentence as a standalone source query retrieves a book's
    cover or table of contents instead of the rule under discussion.  A
    complete query such as ``O que diz o Vade sobre jornada?`` remains a new
    documentary request because it has no continuation bridge.
    """

    normalized = normalize_query_shorthand(question)
    compact = re.sub(r"[!?.,;:]+", " ", normalized)
    compact = re.sub(r"\s+", " ", compact).strip()
    source_reference = bool(
        re.search(r"\b[\w-]+\.(?:md|txt|pdf|docx|xlsx|csv|xml|json)\b", compact)
    ) or any(
        marker in compact
        for marker in (
            "vade",
            "vademecum",
            "mecum",
            "mencum",
            "saae",
            "acordo coletivo",
            "convencao coletiva",
            "outra fonte",
            "outro documento",
            "outro arquivo",
            "essa fonte",
            "esse documento",
            "esse arquivo",
            "manual",
            "norma",
            "lei",
        )
    )
    # New modules do not have to be added to a hard-coded source vocabulary.
    # An explicit noun phrase such as ``documento de indicadores`` or
    # ``manual de operações`` is enough to establish a source handoff.
    source_reference = source_reference or bool(
        re.search(r"\b(?:arquivo|documento|fonte|manual)\s+(?:de|do|da|sobre)?\s*[a-z][\w-]*", compact)
    )
    if not source_reference:
        return False
    return any(
        marker in compact
        for marker in (
            "quando falamos",
            "quando se trata",
            "e quando",
            "e sobre",
            "o que ele diz",
            "o que ela diz",
            "o que esse documento",
            "o que essa fonte",
            "o que diz sobre",
            "o que aparece",
            "o que consta",
            "o que informa",
            "na outra fonte",
            "no outro documento",
            "no outro arquivo",
            "considerando o",
            "em relacao ao",
            "em relacao a",
        )
    )


def _target_collection(module_id: str, question: str) -> str:
    normalized = normalize(question)
    if any(marker in normalized for marker in ("enap", "escola virtual", "curso", "cursos")):
        return "ENAP_CURSOS"
    if module_id == "medicina" and any(marker in normalized for marker in ("paciente", "prontuario", "fhir", "hl7")):
        return "PEP_PACIENTES"
    if module_id == "infraestrutura" and any(marker in normalized for marker in ("zabbix", "trigger", "host", "agent")):
        return "INFRA_ZABBIX"
    if module_id in {"direito", "departamento-pessoal"} and any(marker in normalized for marker in ("lei", "artigo", "clausula", "vade", "jurisprudencia", "acordo")):
        return "LEIS_VADE_MECUM"
    if any(re.search(rf"\b{re.escape(marker)}\b", normalized) for marker in STRUCTURED_MARKERS):
        return "STRUCTURED_DATA"
    return "MODULE_DOCUMENTS"


def _source_hints(question: str) -> tuple[str, ...]:
    hints = list(re.findall(r"\b[\wÀ-ÿ.-]+\.(?:pdf|docx|xlsx|csv|xml|txt|md|json)\b", question, flags=re.IGNORECASE))
    normalized = normalize(question)
    if "enap" in normalized or "escola virtual" in normalized:
        hints.append("ENAP/Escola Virtual Gov")
    if "vade" in normalized:
        hints.append("Vade Mecum")
    if "saae" in normalized:
        hints.append("SAAE")
    return tuple(dict.fromkeys(hints))


def build_query_plan(
    module_id: str,
    question: str,
    task_route: str,
    retrieval_required: bool,
    response_mode: str,
    reason: str = "",
) -> QueryPlan:
    """Build and validate the strict plan consumed by orchestration."""

    exact_term = requested_exact_term(question)
    normalized = normalize(question)
    subqueries = decompose_query(question)
    if exact_term or re.search(r"\b(?:linha|linhas|line|lines)\s*\d+", normalized):
        intent = "BUSCA_EXATA_LINHA"
    elif _list_elements_requested(question):
        intent = "LISTA_ELEMENTOS"
    elif comparison_requested_for_plan(question) or len(_source_hints(question)) >= 2:
        intent = "COMPARACAO_DOCUMENTOS"
    elif task_route == "structured_data" or "correlac" in normalized:
        intent = "STRUCTURED_DATA"
    elif task_route == "tool_action":
        intent = "EXECUCAO_MCP"
    elif task_route == "conversation":
        intent = "CONVERSA_DIRETA"
    elif task_route == "writing":
        intent = "WRITING"
    elif task_route == "complex_reasoning":
        intent = "COMPLEX_REASONING"
    else:
        intent = "DOCUMENT_RAG" if retrieval_required else "CONVERSA_DIRETA"
    return QueryPlan(
        intent=intent,
        target_collection=_target_collection(module_id, question),
        search_term=exact_term,
        requires_exact_match=intent == "BUSCA_EXATA_LINHA",
        source_hints=_source_hints(question),
        retrieval_required=retrieval_required,
        response_mode=response_mode,
        reason=reason,
        subqueries=subqueries,
    )


def _has_contextual_evidence_follow_up(question: str, history: list[dict[str, str]] | None) -> bool:
    """Recognize a follow-up that resumes a documented topic.

    A greeting such as ``me ajuda`` must stay conversational.  Once the prior
    turn contains a verified local answer, a substantive overlap such as
    ``indisponibilidade`` means the user is asking to continue that evidence
    thread, even when they do not repeat ``documento`` or ``fonte``.
    """

    previous = recent_documentary_answer(history)
    if not previous:
        return False
    normalized = normalize(question)
    if any(marker in normalized for marker in ("bom dia", "boa tarde", "boa noite", "obrigado", "obrigada")) and len(normalized.split()) <= 8:
        return False
    stopwords = {
        "ajuda", "ajudar", "quero", "saber", "pode", "podemos", "falar", "fala", "dizer", "diga", "mais",
        "sobre", "isso", "esse", "essa", "aquela", "aquele", "sim", "por", "favor", "vc", "voce", "você",
    }
    question_terms = {term for term in re.findall(r"[\w]+", normalized) if len(term) >= 6 and term not in stopwords}
    previous_terms = set(re.findall(r"[\w]+", normalize(previous)))
    return any(
        question_term == previous_term
        or (
            len(question_term) >= 7
            and len(previous_term) >= 7
            and question_term[:7] == previous_term[:7]
        )
        for question_term in question_terms
        for previous_term in previous_terms
    )


QUERY_PLAN_INTENTS = frozenset(
    {
        "BUSCA_EXATA_LINHA",
        "LISTA_ELEMENTOS",
        "COMPARACAO_DOCUMENTOS",
        "CONVERSA_DIRETA",
        "EXECUCAO_MCP",
        "DOCUMENT_RAG",
        "STRUCTURED_DATA",
        "COMPLEX_REASONING",
        "WRITING",
    }
)
QUERY_PLAN_COLLECTIONS = frozenset(
    {
        "ENAP_CURSOS",
        "PEP_PACIENTES",
        "INFRA_ZABBIX",
        "LEIS_VADE_MECUM",
        "MODULE_DOCUMENTS",
        "STRUCTURED_DATA",
    }
)


@dataclass(frozen=True)
class QueryPlan:
    """Validated execution contract created before retrieval or generation.

    The legacy ``route``/``task_route`` fields remain available to clients,
    but the core now has one explicit plan describing the operation, source
    collection and exact-match requirement.  Providers never choose this
    plan; they receive it only after the retrieval boundary has completed.
    """

    intent: str
    target_collection: str = "MODULE_DOCUMENTS"
    search_term: str = ""
    requires_exact_match: bool = False
    source_hints: tuple[str, ...] = field(default_factory=tuple)
    retrieval_required: bool = True
    response_mode: str = "evidence"
    reason: str = ""
    subqueries: tuple[str, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        if self.intent not in QUERY_PLAN_INTENTS:
            raise ValueError(f"intent de consulta inválida: {self.intent}")
        if self.target_collection not in QUERY_PLAN_COLLECTIONS:
            raise ValueError(f"coleção de consulta inválida: {self.target_collection}")
        if self.response_mode not in {"conversational", "evidence"}:
            raise ValueError(f"modo de resposta inválido: {self.response_mode}")
        if self.requires_exact_match and not self.search_term and self.intent != "BUSCA_EXATA_LINHA":
            raise ValueError("uma consulta exata precisa informar o termo de busca")

    def public_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["source_hints"] = list(self.source_hints)
        return payload

    @classmethod
    def from_mapping(cls, value: Any, *, fallback_intent: str = "DOCUMENT_RAG", retrieval_required: bool = True, response_mode: str = "evidence") -> QueryPlan:
        """Validate a route payload while tolerating legacy clients."""

        if isinstance(value, cls):
            return value
        mapping = value if isinstance(value, dict) else {}
        intent = str(mapping.get("intent") or fallback_intent)
        if intent not in QUERY_PLAN_INTENTS:
            intent = fallback_intent if fallback_intent in QUERY_PLAN_INTENTS else "DOCUMENT_RAG"
        target = str(mapping.get("target_collection") or "MODULE_DOCUMENTS")
        if target not in QUERY_PLAN_COLLECTIONS:
            target = "MODULE_DOCUMENTS"
        hints = mapping.get("source_hints") or ()
        if isinstance(hints, str):
            hints = (hints,)
        return cls(
            intent=intent,
            target_collection=target,
            search_term=str(mapping.get("search_term") or ""),
            requires_exact_match=bool(mapping.get("requires_exact_match", False)),
            source_hints=tuple(str(item) for item in hints if str(item).strip()),
            retrieval_required=bool(mapping.get("retrieval_required", retrieval_required)),
            response_mode=str(mapping.get("response_mode") or response_mode),
            reason=str(mapping.get("reason") or ""),
            subqueries=tuple(
                str(item).strip()
                for item in (mapping.get("subqueries") or ())
                if str(item).strip()
            ) or decompose_query(str(mapping.get("question") or "")),
        )


def route_query(
    module_id: str,
    question: str,
    history: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    """Choose the smallest safe intelligence route for a user request.

    Open-ended help requests are conversational by default.  They only enter
    RAG after the user names a source, asks for a documented rule, requests a
    structured calculation, or supplies enough specificity for an evidence
    task.  ``history`` is deliberately limited to the current session and is
    used only to recognize a conversational follow-up.
    """

    normalized_module = normalize(module_id)
    normalized = normalize(question).strip()
    compact = re.sub(r"[!?.,;:]+", " ", normalized)
    compact = re.sub(r"\s+", " ", compact).strip()
    words = compact.split()
    explicit_evidence = _has_explicit_evidence_request(compact)
    open_conversation = any(marker in compact for marker in OPEN_CONVERSATION_MARKERS)
    conversation_follow_up = _has_conversation_follow_up(question, history)
    contextual_evidence_follow_up = _has_contextual_evidence_follow_up(compact, history)

    def payload(route: str, task_route: str, retrieval_required: bool, response_mode: str, reason: str) -> dict[str, Any]:
        result = _route_payload(route, task_route, retrieval_required, response_mode, reason)
        result["query_plan"] = build_query_plan(
            normalized_module,
            question,
            task_route,
            retrieval_required,
            response_mode,
            reason,
        ).public_dict()
        return result

    if (open_conversation or conversation_follow_up) and not explicit_evidence and not contextual_evidence_follow_up:
        return payload(
            "conversation",
            "conversation",
            False,
            "conversational",
            "pedido aberto ou continuação de conversa sem exigência de evidência interna",
        )

    if contextual_evidence_follow_up and not explicit_evidence:
        return payload(
            "evidence",
            "document_rag",
            True,
            "evidence",
            "continuação de um tema documental já confirmado na sessão",
        )

    if (
        any(compact == marker or compact.startswith(f"{marker} ") for marker in DIRECT_CONVERSATION_MARKERS)
        or (len(words) <= 5 and any(compact.startswith(marker) for marker in ("oi ", "ola ", "olá ")))
    ):
        return payload(
            "conversation",
            "conversation",
            False,
            "conversational",
            "saudação ou conversa sem pedido de evidência interna",
        )

    if any(marker in compact for marker in DIRECT_WRITING_MARKERS) and not explicit_evidence:
        return payload(
            "writing",
            "writing",
            False,
            "conversational",
            "tarefa de escrita sem exigência explícita de fonte interna",
        )

    if any(marker in compact for marker in TOOL_ACTION_MARKERS) and not any(
        marker in compact for marker in ("como ", "o que ", "qual ")
    ):
        return payload(
            "tool",
            "tool_action",
            True,
            "evidence",
            "pedido de ação: validar ferramenta, permissão e evidência antes de executar",
        )

    multi_document = any(
        marker in compact
        for marker in (
            "compare",
            "comparar",
            "comparando",
            "diferenca entre",
            "confronte",
            "cruze os",
            "relacione os documentos",
            "entre os documentos",
            "comum e diferente",
            "o que ha em comum",
            "o que existe em comum",
            "pontos em comum",
            "diferencas entre os dois",
            "diferencas entre ambos",
        )
    ) or len(_source_hints(question)) >= 2
    # Match structured operators as words.  A substring check made ``conte``
    # classify ordinary words such as ``conteúdo`` as a table query, which
    # sent explicit document-line requests through the wrong task contract.
    structured = any(re.search(rf"\b{re.escape(marker)}\b", compact) for marker in STRUCTURED_MARKERS)
    complex_reasoning = any(marker in compact for marker in COMPLEX_REASONING_MARKERS) or bool(re.search(r"\brca\b", compact))
    if explicit_evidence or multi_document or structured or complex_reasoning:
        if multi_document:
            return payload(
                "evidence",
                "multi_document",
                True,
                "evidence",
                "a pergunta exige recuperação e cobertura de mais de uma fonte",
            )
        if structured:
            return payload(
                "evidence",
                "structured_data",
                True,
                "evidence",
                "a pergunta pode exigir leitura integral e cálculo em dados estruturados",
            )
        if complex_reasoning:
            return payload(
                "evidence",
                "complex_reasoning",
                True,
                "evidence",
                "a pergunta exige premissas documentais para inferência ou relação",
            )
        return payload(
            "evidence",
            "document_rag",
            True,
            "evidence",
            "a pergunta referencia conhecimento, documento ou fonte verificável",
        )

    if any(marker in compact for marker in GENERAL_EXPLANATION_MARKERS):
        # Legal and clinical explanations remain local-first because their
        # safety policy requires a source even when the user does not name it.
        protected_module = normalized_module in {"medicina", "direito", "departamento pessoal", "departamento-pessoal"}
        procedure = any(marker in compact for marker in PROCEDURE_MARKERS)
        retrieval_required = protected_module or procedure
        return payload(
            "explanation",
            "general_explanation",
            retrieval_required,
            "evidence" if retrieval_required else "conversational",
            "explicação geral; consultar documentos apenas quando o domínio ou o procedimento exigir evidência",
        )

    # A short, underspecified domain sentence is a conversation opener rather
    # than permission to scan every document in the module.
    if len(words) <= 12 and not explicit_evidence and normalized_module not in {"medicina", "direito", "departamento pessoal", "departamento-pessoal"}:
        return payload(
            "conversation",
            "conversation",
            False,
            "conversational",
            "pedido ainda não especifica uma tarefa ou fonte; solicitar contexto antes de consultar o módulo",
        )

    return payload(
        "explanation",
        "general_explanation",
        normalized_module in {"medicina", "direito", "departamento pessoal", "departamento-pessoal"},
        "evidence" if normalized_module in {"medicina", "direito", "departamento pessoal", "departamento-pessoal"} else "conversational",
        "explicação de domínio sem marcador documental explícito",
    )


def build_conversation_memory(
    module_id: str,
    question: str,
    history: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    """Build bounded, session-scoped memory for the response composer.

    This is not a long-term content store. It exposes only the recent turns,
    a lightweight topic/intent label, detected source/entity hints and the
    assistant's pending question, so a follow-up can remain coherent without
    forcing retrieval or persisting sensitive conversation text.
    """
    turns = [
        {"role": str(item.get("role", "")), "content": str(item.get("content", ""))[:4000]}
        for item in (history or [])[-8:]
        if item.get("role") in {"user", "assistant"} and str(item.get("content", "")).strip()
    ]
    combined = " ".join(item["content"] for item in turns + [{"role": "user", "content": question}])
    normalized = normalize(combined)
    route = route_query(module_id, question, history=[])
    entity_patterns = (
        r"\b[\wÀ-ÿ-]+\.(?:pdf|docx|xlsx|csv|xml|txt)\b",
        r"\b(?:SAAE|Zabbix|FHIR|HL7|CLT|STJ|STF)\b",
    )
    entities: list[str] = []
    for pattern in entity_patterns:
        for match in re.findall(pattern, combined, flags=re.IGNORECASE):
            value = str(match)
            if value.casefold() not in {item.casefold() for item in entities}:
                entities.append(value)
    pending_question = ""
    for item in reversed(turns):
        if item["role"] == "assistant" and "?" in item["content"]:
            pending_question = item["content"].strip()[:500]
            break
    topic_terms = [
        term
        for term in re.findall(r"[\wÀ-ÿ]{4,}", normalize(question))
        if term not in {"para", "sobre", "como", "qual", "esse", "esta", "problema", "ajuda"}
    ]
    return {
        "topic": " ".join(dict.fromkeys(topic_terms[:8])) or normalize(module_id),
        "intent": route.get("task_route", route.get("route", "conversation")),
        "entities": entities[:12],
        "context_recent": turns[-6:],
        "pending_question": pending_question,
        "module": module_id,
        "has_context": bool(turns),
        "context_terms": sorted(set(re.findall(r"[\wÀ-ÿ]{5,}", normalized)))[:24],
    }


def _with_route(
    profile: dict[str, Any],
    module_id: str,
    question: str,
    history: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    enriched = dict(profile)
    enriched.update(route_query(module_id, question, history=history))
    return enriched


def assess_module_scope(module_id: str, question: str) -> dict[str, Any]:
    """Explain whether a question appears aligned with the active module."""
    normalized = normalize(question)
    scores: dict[str, tuple[int, list[str]]] = {}
    for candidate, terms in MODULE_SCOPE_TERMS.items():
        matched = [term for term in terms if normalize(term) in normalized]
        if matched:
            scores[candidate] = (len(matched), matched[:4])
    current_score, current_terms = scores.get(module_id, (0, []))
    other_scores = [(score, candidate, terms) for candidate, (score, terms) in scores.items() if candidate != module_id]
    other_scores.sort(reverse=True)
    best_other = other_scores[0] if other_scores else (0, "", [])
    shared_only = bool(best_other[1]) and bool(best_other[2]) and all(
        _is_shared_scope_term(module_id, best_other[1], term) for term in best_other[2]
    )
    external_topic = _explicit_out_of_scope_topic(normalized, current_score)
    if external_topic:
        topic, topic_terms = external_topic
        status = "outside"
        confidence = "high"
        related_module = "__out_of_scope__"
        current_terms = topic_terms
        related_name = topic
    elif current_score > 0 and current_score >= best_other[0]:
        status = "aligned"
        confidence = "high" if current_score >= 2 else "medium"
        related_module = module_id
        related_name = MODULE_NAMES.get(related_module, related_module)
    elif best_other[0] > 0 and not shared_only and not (
        best_other[0] == 1 and any(term in normalized for term in GENERIC_ANALYSIS_TERMS)
    ):
        status = "outside"
        confidence = "medium"
        related_module = best_other[1]
        current_terms = best_other[2]
        related_name = MODULE_NAMES.get(related_module, related_module)
    else:
        status = "uncertain"
        confidence = "low"
        related_module = module_id
        related_name = MODULE_NAMES.get(related_module, related_module)
    return {
        "status": status,
        "confidence": confidence,
        "module_id": module_id,
        "module_name": MODULE_NAMES.get(module_id, module_id),
        "related_module_id": related_module,
        "related_module_name": related_name,
        "matched_terms": current_terms,
    }


def classify_query(
    module_id: str,
    question: str,
    history: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    """Return a privacy-safe semantic label used by retrieval and analytics.

    This is intentionally a small, explainable taxonomy. It routes a query to
    the right evidence profile; it never generates medical or legal conclusions.
    """
    normalized = normalize(question)
    tokens = set(re.findall(r"[\w]+", normalized))

    if module_id == "medicina" and is_medical_sleep_query(question):
        return _with_route({
            "intent": "clinical_symptom_assessment",
            "theme": "Sono e sonolência",
            "concepts": [
                "sonolência diurna",
                "microssono",
                "privação de sono",
                "sono insuficiente",
            ],
            "risk_flags": ["acidente_por_sonolencia"],
            "source_profile": "clinical_guideline",
        }, module_id, question, history)

    if module_id == "medicina":
        if any(term in normalized for term in ("sintoma", "dor", "febre", "tosse", "gripe", "influenza")):
            return _with_route({
                "intent": "clinical_symptom_assessment",
                "theme": "Sintomas e avaliação clínica",
                "concepts": ["sintomas", "avaliação clínica"],
                "risk_flags": ["avaliacao_profissional"],
                "source_profile": "clinical_guideline",
            }, module_id, question, history)
        if any(term in normalized for term in ("paciente", "prontuario", "fhir", "exame", "tratamento")):
            return _with_route({
                "intent": "clinical_record_or_protocol",
                "theme": "Protocolos e registros clínicos",
                "concepts": ["protocolo", "registro clínico", "FHIR"],
                "risk_flags": ["dados_de_saude"],
                "source_profile": "clinical_guideline",
            }, module_id, question, history)
        return _with_route({
            "intent": "medical_knowledge_lookup",
            "theme": "Conhecimento médico",
            "concepts": sorted(tokens)[:8],
            "risk_flags": ["avaliacao_profissional"],
            "source_profile": "clinical_guideline",
        }, module_id, question, history)

    if module_id in {"direito", "departamento-pessoal"}:
        if any(term in normalized for term in ("hora extra", "horas extras", "jornada", "hora negativa", "banco de horas")):
            theme = "Jornada, horas extras e compensação"
        elif any(term in normalized for term in ("acordo coletivo", "convencao coletiva", "saae")):
            theme = "Acordo coletivo e interpretação"
        elif any(term in normalized for term in ("ferias", "salario", "decimo terceiro", "13")):
            theme = "Direitos trabalhistas e remuneração"
        else:
            theme = "Legislação e documentos"
        return _with_route({
            "intent": "legal_document_analysis",
            "theme": theme,
            "concepts": sorted(tokens)[:8],
            "risk_flags": ["revisao_juridica"],
            "source_profile": "legal_primary_source",
        }, module_id, question, history)

    if module_id == "infraestrutura":
        if any(term in normalized for term in ("zabbix", "host", "monitoramento", "agent")):
            theme = "Zabbix e monitoramento"
        elif any(term in normalized for term in ("rede", "scan", "scanner", "snmp", "tcp", "udp")):
            theme = "Redes e diagnóstico"
        elif any(term in normalized for term in ("sistema operacional", "linux", "windows", "servidor")):
            theme = "Sistemas e disponibilidade"
        else:
            theme = "Infraestrutura e operações"
        return _with_route({
            "intent": "technical_procedure_or_diagnosis",
            "theme": theme,
            "concepts": sorted(tokens)[:8],
            "risk_flags": [],
            "source_profile": "technical_documentation",
        }, module_id, question, history)

    if module_id == "gestao-empresarial" and (
        ("desvio" in normalized or "variacao" in normalized)
        and "producao" in normalized
    ):
        return _with_route({
            "intent": "production_variance_analysis",
            "theme": "Desvios de produção e indicadores",
            "concepts": ["produção", "meta", "realizado", "desvio", "indicadores"],
            "risk_flags": [],
            "source_profile": "module_document",
        }, module_id, question, history)

    return _with_route({
        "intent": "module_knowledge_lookup",
        "theme": "Outros temas do módulo",
        "concepts": sorted(tokens)[:8],
        "risk_flags": [],
        "source_profile": "module_document",
    }, module_id, question, history)
